Repository CSE210-G13/my-roommates, pull requests merged in 2023-03, with the labels that each got.

#53 Edit profile page - loading and saving user information from backend
  src/components/EditProfile/EditPersonalInformationForm.js
  src/components/EditProfile/EditProfile.js
  src/components/EditProfile/EditPropertyPrefForm.js
  src/components/EditProfile/EditRoommatePrefForm.js
  src/components/FirstTimeUserFlow/FirstTimeUserFlow.js
  src/components/NavBar/NavBar.js
  src/firebase/classes.js
  src/firebase/userDb.js
Labels: enhancement

#61 Roommates page: load data from backend
  src/components/EditProfile/EditPersonalInformationForm.js
  src/components/EditProfile/EditPropertyPrefForm.js
  src/components/FirstTimeUserFlow/PersonalInfoForm.js
  src/components/RoommateGrid/RoommateCard.js
  src/constants/constants.js
  src/firebase/classes.js
  src/firebase/userDb.js
  src/pages/roommates.js
Labels: db

#72 David/like button
  src/components/PropertyCard/PropertyCard.js
  src/components/PropertyFilter/PropertyFilter.js
  src/firebase/userLikedProperties.js
  src/pages/properties.js
  src/pages/property/[uid].js
Labels: ui, db

#89 Additional Friend Request Functionality
  src/components/EditProfile/EditPersonalInformationForm.js
  src/components/FriendRequest/FriendList.js
  src/components/UserProfile/UserHeader.js
Labels: enhancement

#90 fix: error on properties page
  src/components/PropertyCard/PropertyCardActions.js
Labels: bug

#87 David/cypress test
  .gitignore
  cypress.config.ts
  package.json
  src/components/FirstTimeUserFlow/FirstTimeUserFlow.js
  src/test/e2e/index.cy.js
  src/test/firstTimeUser.test.js
  src/test/home.cy.js
  src/test/index.test.js
Labels: test
